#ifndef RENDER_DEFINES_H
#define RENDER_DEFINES_H

#define SHADOW_MAP_WIDTH 2048
#define SHADOW_MAP_HEIGHT 2048

enum TextureSlots : int {
  ATLAS_TEXTURE_SLOT = 0,
  DIFFUSE_TEXTURE_SLOT,
  SHADOW_MAP_TEXTURE_SLOT,
  HDR_TEXTURE_SLOT,
  ATLAS_NORMAL_TEXTURE_SLOT,
  ATLAS_ALBEDO_TEXTURE_SLOT,
  ATLAS_AO_TEXTURE_SLOT,
  ATLAS_ROUGHNESS_TEXTURE_SLOT,
  ATLAS_METALLIC_TEXTURE_SLOT,
};

#endif
