#ifndef RENDER_DEFINES_H
#define RENDER_DEFINES_H

#define SHADOW_MAP_WIDTH 2048
#define SHADOW_MAP_HEIGHT 2048

#define ATLAS_TEXTURE_SLOT 0
#define DIFFUSE_TEXTURE_SLOT 1
#define SHADOW_MAP_TEXTURE_SLOT 2
#define HDR_TEXTURE_SLOT 3
#define NORMAL_ATLAS_TEXTURE_SLOT 4

#endif
